# Generated by Django 3.2.9 on 2021-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
