# Generated by Django 3.2.9 on 2021-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
