# Generated by Django 3.2.9 on 2021-12-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211208_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
