# Generated by Django 3.2.9 on 2021-12-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211208_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_cart',
            field=models.TextField(default=''),
        ),
    ]
