# Generated by Django 3.2.9 on 2022-01-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_game'),
        ('wishlists', '0004_alter_wishlist_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='products.game'),
        ),
    ]
