# Generated by Django 3.2.9 on 2022-01-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_game'),
        ('wishlists', '0006_auto_20220101_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_game',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='products.game'),
        ),
    ]
