# Generated by Django 3.2.9 on 2022-01-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_game'),
        ('wishlists', '0007_auto_20220101_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='game',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.game'),
            preserve_default=False,
        ),
    ]
