# Generated by Django 3.2.9 on 2022-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0008_auto_20220101_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_game',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='game_ids',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
