# Generated by Django 3.2.9 on 2022-01-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0009_auto_20220101_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='title',
        ),
    ]
